using System.Text.Json.Serialization;

namespace TheHive.Api.Data.Authentication;

/// <summary>
/// The body of an activate-TOTP request (the spec's <c>InputTOTPCode</c>). Both members are secrets: they are sent in the JSON body only and this class does not print them.
/// </summary>
public sealed class TotpActivateRequest
{
	/// <summary>The current 6-digit code generated by the authenticator app from <see cref="Secret"/>. SECRET. The spec types it as an integer, so a code with leading zeros loses them (verify).</summary>
	[JsonPropertyName("code")]
	public required int Code { get; set; }

	/// <summary>The secret returned by <c>IAuthentication.GetTotpSecretAsync</c>. SECRET.</summary>
	[JsonPropertyName("secret")]
	public required string Secret { get; set; }
}
