using System.Text.Json;
using System.Text.Json.Serialization;

namespace TheHive.Api.Data.AuditTrail;

/// <summary>An audit log entry describing a change (the spec's <c>OutputAudit</c>). Entries are immutable, so <see cref="UpdatedBy"/> and <see cref="UpdatedAt"/> are normally absent.</summary>
public sealed class AuditEntry
{
	/// <summary>The internal identifier of the entry (for example <c>~327684328</c>).</summary>
	[JsonPropertyName("_id")]
	public string Id { get; set; } = string.Empty;

	/// <summary>The entity type, always <c>Audit</c>.</summary>
	[JsonPropertyName("_type")]
	public string Type { get; set; } = string.Empty;

	/// <summary>The login of the user who performed the action.</summary>
	[JsonPropertyName("_createdBy")]
	public string CreatedBy { get; set; } = string.Empty;

	/// <summary>The login of the user who last updated the entry; always absent in practice.</summary>
	[JsonPropertyName("_updatedBy")]
	public string? UpdatedBy { get; set; }

	/// <summary>When the action occurred.</summary>
	[JsonPropertyName("_createdAt")]
	public DateTimeOffset CreatedAt { get; set; }

	/// <summary>When the entry was last updated; always absent in practice.</summary>
	[JsonPropertyName("_updatedAt")]
	public DateTimeOffset? UpdatedAt { get; set; }

	/// <summary>The type of action recorded: <c>create</c>, <c>update</c>, <c>delete</c>, <c>merge</c>, or <c>invoke</c> for a function call.</summary>
	[JsonPropertyName("action")]
	public string Action { get; set; } = string.Empty;

	/// <summary>The identifier of the HTTP request that triggered the entry; every entry generated by the same request shares it.</summary>
	[JsonPropertyName("requestId")]
	public string RequestId { get; set; } = string.Empty;

	/// <summary>The identifier of the parent object, for example the case when a task is modified.</summary>
	[JsonPropertyName("rootId")]
	public string RootId { get; set; } = string.Empty;

	/// <summary>The modified fields and their new values (an object).</summary>
	[JsonPropertyName("details")]
	public JsonElement? Details { get; set; }

	/// <summary>The identifier of the directly affected object, if any.</summary>
	[JsonPropertyName("objectId")]
	public string? ObjectId { get; set; }

	/// <summary>The type of the directly affected object (for example <c>Case</c>), if any.</summary>
	[JsonPropertyName("objectType")]
	public string? ObjectType { get; set; }

	/// <summary>The affected object as it is now, not as it was at the time of the action; absent if it has since been deleted.</summary>
	[JsonPropertyName("object")]
	public JsonElement? Object { get; set; }

	/// <summary>The parent object referenced by <see cref="RootId"/> as it is now; absent if it has since been deleted.</summary>
	[JsonPropertyName("context")]
	public JsonElement? Context { get; set; }

	/// <summary>Whether this entry is the primary action rather than a derived event (for example one that also affects another organization through a sharing rule).</summary>
	[JsonPropertyName("mainAction")]
	public bool MainAction { get; set; }
}
